### ISSUE TITLE
Create Release Strategy

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort-governance#20]
Define the release strategy for ORT.

- How often are releases made?
- What are the guarantees regarding backward compatibility or API stability?
- Which versioning scheme is used (#18)?

**Comment by sschuberth** [comment]
ORT does weekly releases since https://github.com/oss-review-toolkit/ort/releases/tag/1.0.0. Breaking changes are marked as such and bump the major version according to SemVer. There is no release management / maintenance in the sense of back-porting bug fixes to older versions without breaking changes, simply due to time constraints.
